-- *********************************************************************
-- POST-Update Database Script from 3.2.0-CR1-SNAPTSHOT to 3.2.0.Final
-- *********************************************************************

ALTER TABLE public.REALM DROP COLUMN DOCKER_AUTH_FLOW;
ALTER TABLE IF EXISTS public.REALM RENAME DOCKER_AUTH_FLOW_OLD to DOCKER_AUTH_FLOW;

DROP INDEX IF EXISTS IDX_ASSOC_POL_ASSOC_POL_ID;
ALTER INDEX IF EXISTS IDX_ASSOC_POL_ASSOC_POL_ID_OLD RENAME TO IDX_ASSOC_POL_ASSOC_POL_ID;

DROP INDEX IF EXISTS IDX_AUTH_EXEC_REALM_FLOW;
ALTER INDEX IF EXISTS IDX_AUTH_EXEC_REALM_FLOW_OLD RENAME TO IDX_AUTH_EXEC_REALM_FLOW;

DROP INDEX IF EXISTS IDX_AUTH_EXEC_FLOW;
ALTER INDEX IF EXISTS IDX_AUTH_EXEC_FLOW_OLD RENAME TO IDX_AUTH_EXEC_FLOW;

DROP INDEX IF EXISTS IDX_AUTH_FLOW_REALM;
ALTER INDEX IF EXISTS IDX_AUTH_FLOW_REALM_OLD RENAME TO IDX_AUTH_FLOW_REALM;

DROP INDEX IF EXISTS IDX_AUTH_CONFIG_REALM;
ALTER INDEX IF EXISTS IDX_AUTH_CONFIG_REALM_OLD RENAME TO IDX_AUTH_CONFIG_REALM;

DROP INDEX IF EXISTS IDX_CLIENT_CLIENT_TEMPL_ID;
ALTER INDEX IF EXISTS IDX_CLIENT_CLIENT_TEMPL_ID_OLD RENAME TO IDX_CLIENT_CLIENT_TEMPL_ID;

DROP INDEX IF EXISTS IDX_CLIENT_DEF_ROLES_CLIENT;
ALTER INDEX IF EXISTS IDX_CLIENT_DEF_ROLES_CLIENT_OLD RENAME TO IDX_CLIENT_DEF_ROLES_CLIENT;

DROP INDEX IF EXISTS IDX_CLIENT_ID_PROV_MAP_CLIENT;
ALTER INDEX IF EXISTS IDX_CLIENT_ID_PROV_MAP_CLIENT_OLD RENAME TO IDX_CLIENT_ID_PROV_MAP_CLIENT;

DROP INDEX IF EXISTS IDX_CLIENT_SESSION_SESSION;
ALTER INDEX IF EXISTS IDX_CLIENT_SESSION_SESSION_OLD RENAME TO IDX_CLIENT_SESSION_SESSION;

DROP INDEX IF EXISTS IDX_COMPONENT_REALM;
ALTER INDEX IF EXISTS IDX_COMPONENT_REALM_OLD RENAME TO IDX_COMPONENT_REALM;

DROP INDEX IF EXISTS IDX_COMPO_CONFIG_COMPO;
ALTER INDEX IF EXISTS IDX_COMPO_CONFIG_COMPO_OLD RENAME TO IDX_COMPO_CONFIG_COMPO;

DROP INDEX IF EXISTS IDX_COMPONENT;
ALTER INDEX IF EXISTS IDX_COMPONENT_OLD RENAME TO IDX_COMPONENT;

DROP INDEX IF EXISTS IDX_COMPOSITE_CHILD;
ALTER INDEX IF EXISTS IDX_COMPOSITE_CHILD_OLD RENAME TO IDX_COMPOSITE_CHILD;

DROP INDEX IF EXISTS IDX_CREDENTIAL_ATTR_CRED;
ALTER INDEX IF EXISTS IDX_CREDENTIAL_ATTR_CRED_OLD RENAME TO IDX_CREDENTIAL_ATTR_CRED;

DROP INDEX IF EXISTS IDX_FED_CRED_ATTR_CRED;
ALTER INDEX IF EXISTS IDX_FED_CRED_ATTR_CRED_OLD RENAME TO IDX_FED_CRED_ATTR_CRED;

DROP INDEX IF EXISTS IDX_GROUP_ATTR_GROUP;
ALTER INDEX IF EXISTS IDX_GROUP_ATTR_GROUP_OLD RENAME TO IDX_GROUP_ATTR_GROUP;

DROP INDEX IF EXISTS IDX_GROUP_ROLE_MAPP_GROUP;
ALTER INDEX IF EXISTS IDX_GROUP_ROLE_MAPP_GROUP_OLD RENAME TO IDX_GROUP_ROLE_MAPP_GROUP;

DROP INDEX IF EXISTS IDX_IDENT_PROV_REALM;
ALTER INDEX IF EXISTS IDX_IDENT_PROV_REALM_OLD RENAME TO IDX_IDENT_PROV_REALM;

DROP INDEX IF EXISTS IDX_ID_PROV_MAPP_REALM;
ALTER INDEX IF EXISTS IDX_ID_PROV_MAPP_REALM_OLD RENAME TO IDX_ID_PROV_MAPP_REALM;

DROP INDEX IF EXISTS IDX_KEYCLOAK_ROLE_CLIENT;
ALTER INDEX IF EXISTS IDX_KEYCLOAK_ROLE_CLIENT_OLD RENAME TO IDX_KEYCLOAK_ROLE_CLIENT;

DROP INDEX IF EXISTS IDX_KEYCLOAK_ROLE_REALM;
ALTER INDEX IF EXISTS IDX_KEYCLOAK_ROLE_REALM_OLD RENAME TO IDX_KEYCLOAK_ROLE_REALM;

DROP INDEX IF EXISTS IDX_PROTOCOL_MAPPER_CLIENT;
ALTER INDEX IF EXISTS IDX_PROTOCOL_MAPPER_CLIENT_OLD RENAME TO IDX_PROTOCOL_MAPPER_CLIENT;

DROP INDEX IF EXISTS IDX_PROTO_MAPP_CLIENT_TEMPL;
ALTER INDEX IF EXISTS IDX_PROTO_MAPP_CLIENT_TEMPL_OLD RENAME TO IDX_PROTO_MAPP_CLIENT_TEMPL;

DROP INDEX IF EXISTS IDX_REALM_MASTER_ADM_CLI;
ALTER INDEX IF EXISTS IDX_REALM_MASTER_ADM_CLI_OLD RENAME TO IDX_REALM_MASTER_ADM_CLI;

DROP INDEX IF EXISTS IDX_REALM_ATTR_REALM;
ALTER INDEX IF EXISTS IDX_REALM_ATTR_REALM_OLD RENAME TO IDX_REALM_ATTR_REALM;

DROP INDEX IF EXISTS IDX_REALM_DEF_GRP_REALM;
ALTER INDEX IF EXISTS IDX_REALM_DEF_GRP_REALM_OLD RENAME TO IDX_REALM_DEF_GRP_REALM;

DROP INDEX IF EXISTS IDX_REALM_DEF_ROLES_REALM;
ALTER INDEX IF EXISTS IDX_REALM_DEF_ROLES_REALM_OLD RENAME TO IDX_REALM_DEF_ROLES_REALM;

DROP INDEX IF EXISTS IDX_REALM_EVT_TYPES_REALM;
ALTER INDEX IF EXISTS IDX_REALM_EVT_TYPES_REALM_OLD RENAME TO IDX_REALM_EVT_TYPES_REALM;

DROP INDEX IF EXISTS IDX_REALM_EVT_LIST_REALM;
ALTER INDEX IF EXISTS IDX_REALM_EVT_LIST_REALM_OLD RENAME TO IDX_REALM_EVT_LIST_REALM;

DROP INDEX IF EXISTS IDX_REALM_SUPP_LOCAL_REALM;
ALTER INDEX IF EXISTS IDX_REALM_SUPP_LOCAL_REALM_OLD RENAME TO IDX_REALM_SUPP_LOCAL_REALM;

DROP INDEX IF EXISTS IDX_REDIR_URI_CLIENT;
ALTER INDEX IF EXISTS IDX_REDIR_URI_CLIENT_OLD RENAME TO IDX_REDIR_URI_CLIENT;

DROP INDEX IF EXISTS IDX_REQ_ACT_PROV_REALM;
ALTER INDEX IF EXISTS IDX_REQ_ACT_PROV_REALM_OLD RENAME TO IDX_REQ_ACT_PROV_REALM;

DROP INDEX IF EXISTS IDX_RES_POLICY_POLICY;
ALTER INDEX IF EXISTS IDX_RES_POLICY_POLICY_OLD RENAME TO IDX_RES_POLICY_POLICY;

DROP INDEX IF EXISTS IDX_RES_SCOPE_SCOPE;
ALTER INDEX IF EXISTS IDX_RES_SCOPE_SCOPE_OLD RENAME TO IDX_RES_SCOPE_SCOPE;

DROP INDEX IF EXISTS IDX_RES_SERV_POL_RES_SERV;
ALTER INDEX IF EXISTS IDX_RES_SERV_POL_RES_SERV_OLD RENAME TO IDX_RES_SERV_POL_RES_SERV;

DROP INDEX IF EXISTS IDX_RES_SRV_RES_RES_SRV;
ALTER INDEX IF EXISTS IDX_RES_SRV_RES_RES_SRV_OLD RENAME TO IDX_RES_SRV_RES_RES_SRV;

DROP INDEX IF EXISTS IDX_RES_SRV_SCOPE_RES_SRV;
ALTER INDEX IF EXISTS IDX_RES_SRV_SCOPE_RES_SRV_OLD RENAME TO IDX_RES_SRV_SCOPE_RES_SRV;

DROP INDEX IF EXISTS IDX_SCOPE_MAPPING_ROLE;
ALTER INDEX IF EXISTS IDX_SCOPE_MAPPING_ROLE_OLD RENAME TO IDX_SCOPE_MAPPING_ROLE;

DROP INDEX IF EXISTS IDX_SCOPE_POLICY_POLICY;
ALTER INDEX IF EXISTS IDX_SCOPE_POLICY_POLICY_OLD RENAME TO IDX_SCOPE_POLICY_POLICY;

DROP INDEX IF EXISTS IDX_TEMPL_SCOPE_MAPP_ROLE;
ALTER INDEX IF EXISTS IDX_TEMPL_SCOPE_MAPP_ROLE_OLD RENAME TO IDX_TEMPL_SCOPE_MAPP_ROLE;

DROP INDEX IF EXISTS IDX_USR_FED_MAP_FED_PRV;
ALTER INDEX IF EXISTS IDX_USR_FED_MAP_FED_PRV_OLD RENAME TO IDX_USR_FED_MAP_FED_PRV;

DROP INDEX IF EXISTS IDX_USR_FED_MAP_REALM;
ALTER INDEX IF EXISTS IDX_USR_FED_MAP_REALM_OLD RENAME TO IDX_USR_FED_MAP_REALM;

DROP INDEX IF EXISTS IDX_USR_FED_PRV_REALM;
ALTER INDEX IF EXISTS IDX_USR_FED_PRV_REALM_OLD RENAME TO IDX_USR_FED_PRV_REALM;

DROP INDEX IF EXISTS IDX_WEB_ORIG_CLIENT;
ALTER INDEX IF EXISTS IDX_WEB_ORIG_CLIENT_OLD RENAME TO IDX_WEB_ORIG_CLIENT;

DROP INDEX IF EXISTS IDX_CLIENT_INIT_ACC_REALM;
ALTER INDEX IF EXISTS IDX_CLIENT_INIT_ACC_REALM_OLD RENAME TO IDX_CLIENT_INIT_ACC_REALM;

