-- *********************************************************************
-- PRE-Update Database Script from 3.2.0-CR1-SNAPTSHOT to 3.2.0.Final
-- *********************************************************************

BEGIN;

SELECT 1;

SAVEPOINT sp;

-- ALTER TABLE IF EXISTS public.REALM RENAME DOCKER_AUTH_FLOW to DOCKER_AUTH_FLOW_OLD;
ALTER TABLE public.OFFLINE_CLIENT_SESSION ADD CONSTRAINT CONSTRAINT_OFFL_CL_SES_PK2 CHECK (offline_flag IS NOT NULL);
ALTER TABLE public.OFFLINE_CLIENT_SESSION ADD CLIENT_SESSION_ID VARCHAR(36);
DROP TABLE IF EXISTS public.CLIENT_INITIAL_ACCESS;
ALTER TABLE IF EXISTS public.OFFLINE_CLIENT_SESSION DROP CONSTRAINT CONSTRAINT_OFFL_CL_SES_PK3;
ALTER INDEX IF EXISTS IDX_ASSOC_POL_ASSOC_POL_ID RENAME TO IDX_ASSOC_POL_ASSOC_POL_ID_OLD;
ALTER INDEX IF EXISTS IDX_AUTH_EXEC_REALM_FLOW RENAME TO IDX_AUTH_EXEC_REALM_FLOW_OLD;
ALTER INDEX IF EXISTS IDX_AUTH_EXEC_FLOW RENAME TO IDX_AUTH_EXEC_FLOW_OLD;
ALTER INDEX IF EXISTS IDX_AUTH_FLOW_REALM RENAME TO IDX_AUTH_FLOW_REALM_OLD;
ALTER INDEX IF EXISTS IDX_AUTH_CONFIG_REALM RENAME TO IDX_AUTH_CONFIG_REALM_OLD;
ALTER INDEX IF EXISTS IDX_CLIENT_CLIENT_TEMPL_ID RENAME TO IDX_CLIENT_CLIENT_TEMPL_ID_OLD;
ALTER INDEX IF EXISTS IDX_CLIENT_DEF_ROLES_CLIENT RENAME TO IDX_CLIENT_DEF_ROLES_CLIENT_OLD;
ALTER INDEX IF EXISTS IDX_CLIENT_ID_PROV_MAP_CLIENT RENAME TO IDX_CLIENT_ID_PROV_MAP_CLIENT_OLD;
ALTER INDEX IF EXISTS IDX_CLIENT_SESSION_SESSION RENAME TO IDX_CLIENT_SESSION_SESSION_OLD;
ALTER INDEX IF EXISTS IDX_COMPONENT_REALM RENAME TO IDX_COMPONENT_REALM_OLD;
ALTER INDEX IF EXISTS IDX_COMPO_CONFIG_COMPO RENAME TO IDX_COMPO_CONFIG_COMPO_OLD;
ALTER INDEX IF EXISTS IDX_COMPOSITE RENAME TO IDX_COMPOSITE_OLD;
ALTER INDEX IF EXISTS IDX_COMPOSITE_CHILD RENAME TO IDX_COMPOSITE_CHILD_OLD;
ALTER INDEX IF EXISTS IDX_CREDENTIAL_ATTR_CRED RENAME TO IDX_CREDENTIAL_ATTR_CRED_OLD;
ALTER INDEX IF EXISTS IDX_FED_CRED_ATTR_CRED RENAME TO IDX_FED_CRED_ATTR_CRED_OLD;
ALTER INDEX IF EXISTS IDX_GROUP_ATTR_GROUP RENAME TO IDX_GROUP_ATTR_GROUP_OLD;
ALTER INDEX IF EXISTS IDX_GROUP_ROLE_MAPP_GROUP RENAME TO IDX_GROUP_ROLE_MAPP_GROUP_OLD;
ALTER INDEX IF EXISTS IDX_IDENT_PROV_REALM RENAME TO IDX_IDENT_PROV_REALM_OLD;
ALTER INDEX IF EXISTS IDX_ID_PROV_MAPP_REALM RENAME TO IDX_ID_PROV_MAPP_REALM_OLD;
ALTER INDEX IF EXISTS IDX_KEYCLOAK_ROLE_CLIENT RENAME TO IDX_KEYCLOAK_ROLE_CLIENT_OLD;
ALTER INDEX IF EXISTS IDX_KEYCLOAK_ROLE_REALM RENAME TO IDX_KEYCLOAK_ROLE_REALM_OLD;
ALTER INDEX IF EXISTS IDX_PROTOCOL_MAPPER_CLIENT RENAME TO IDX_PROTOCOL_MAPPER_CLIENT_OLD;
ALTER INDEX IF EXISTS IDX_PROTO_MAPP_CLIENT_TEMPL RENAME TO IDX_PROTO_MAPP_CLIENT_TEMPL_OLD;
ALTER INDEX IF EXISTS IDX_REALM_MASTER_ADM_CLI RENAME TO IDX_REALM_MASTER_ADM_CLI_OLD;
ALTER INDEX IF EXISTS IDX_REALM_ATTR_REALM RENAME TO IDX_REALM_ATTR_REALM_OLD;
ALTER INDEX IF EXISTS IDX_REALM_DEF_GRP_REALM RENAME TO IDX_REALM_DEF_GRP_REALM_OLD;
ALTER INDEX IF EXISTS IDX_REALM_DEF_ROLES_REALM RENAME TO IDX_REALM_DEF_ROLES_REALM_OLD;
ALTER INDEX IF EXISTS IDX_REALM_EVT_TYPES_REALM RENAME TO IDX_REALM_EVT_TYPES_REALM_OLD;
ALTER INDEX IF EXISTS IDX_REALM_EVT_LIST_REALM RENAME TO IDX_REALM_EVT_LIST_REALM_OLD;
ALTER INDEX IF EXISTS IDX_REALM_SUPP_LOCAL_REALM RENAME TO IDX_REALM_SUPP_LOCAL_REALM_OLD;
ALTER INDEX IF EXISTS IDX_REDIR_URI_CLIENT RENAME TO IDX_REDIR_URI_CLIENT_OLD;
ALTER INDEX IF EXISTS IDX_REQ_ACT_PROV_REALM RENAME TO IDX_REQ_ACT_PROV_REALM_OLD;
ALTER INDEX IF EXISTS IDX_RES_POLICY_POLICY RENAME TO IDX_RES_POLICY_POLICY_OLD;
ALTER INDEX IF EXISTS IDX_RES_SCOPE_SCOPE RENAME TO IDX_RES_SCOPE_SCOPE_OLD;
ALTER INDEX IF EXISTS IDX_RES_SERV_POL_RES_SERV RENAME TO IDX_RES_SERV_POL_RES_SERV_OLD;
ALTER INDEX IF EXISTS IDX_RES_SRV_RES_RES_SRV RENAME TO IDX_RES_SRV_RES_RES_SRV_OLD;
ALTER INDEX IF EXISTS IDX_RES_SRV_SCOPE_RES_SRV RENAME TO IDX_RES_SRV_SCOPE_RES_SRV_OLD;
ALTER INDEX IF EXISTS IDX_SCOPE_MAPPING_ROLE RENAME TO IDX_SCOPE_MAPPING_ROLE_OLD;
ALTER INDEX IF EXISTS IDX_SCOPE_POLICY_POLICY RENAME TO IDX_SCOPE_POLICY_POLICY_OLD;
ALTER INDEX IF EXISTS IDX_TEMPL_SCOPE_MAPP_ROLE RENAME TO IDX_TEMPL_SCOPE_MAPP_ROLE_OLD;
ALTER INDEX IF EXISTS IDX_USR_FED_MAP_FED_PRV RENAME TO IDX_USR_FED_MAP_FED_PRV_OLD;
ALTER INDEX IF EXISTS IDX_USR_FED_MAP_REALM RENAME TO IDX_USR_FED_MAP_REALM_OLD;
ALTER INDEX IF EXISTS IDX_USR_FED_PRV_REALM RENAME TO IDX_USR_FED_PRV_REALM_OLD;
ALTER INDEX IF EXISTS IDX_WEB_ORIG_CLIENT RENAME TO IDX_WEB_ORIG_CLIENT_OLD;
ALTER INDEX IF EXISTS IDX_CLIENT_INIT_ACC_REALM RENAME TO IDX_CLIENT_INIT_ACC_REALM_OLD;

RELEASE sp;
SAVEPOINT sp;
ROLLBACK TO SAVEPOINT sp;
RELEASE sp;

COMMIT;