-- *********************************************************************
-- Update Database Script
-- *********************************************************************
-- Change Log: META-INF/jpa-changelog-master.xml
-- Ran at: 7/24/17 10:34 PM
-- Against: keycloak@jdbc:postgresql://keycloak-postgresql:5432/keycloak
-- Liquibase version: 3.4.1
-- *********************************************************************

-- Changeset META-INF/jpa-changelog-3.2.0.xml::3.2.0::keycloak
ALTER TABLE public.REALM ADD DOCKER_AUTH_FLOW VARCHAR(36);

ALTER TABLE public.OFFLINE_CLIENT_SESSION DROP CONSTRAINT CONSTRAINT_OFFL_CL_SES_PK2;

ALTER TABLE public.OFFLINE_CLIENT_SESSION DROP COLUMN CLIENT_SESSION_ID;

ALTER TABLE public.OFFLINE_CLIENT_SESSION ADD CONSTRAINT CONSTRAINT_OFFL_CL_SES_PK3 PRIMARY KEY (USER_SESSION_ID, CLIENT_ID, OFFLINE_FLAG);

CREATE TABLE public.CLIENT_INITIAL_ACCESS (ID VARCHAR(36) NOT NULL, REALM_ID VARCHAR(36), TIMESTAMP INT, EXPIRATION INT, COUNT INT, REMAINING_COUNT INT);

ALTER TABLE public.CLIENT_INITIAL_ACCESS ADD CONSTRAINT CNSTR_CLIENT_INIT_ACC_PK PRIMARY KEY (ID);

ALTER TABLE public.CLIENT_INITIAL_ACCESS ADD CONSTRAINT FK_CLIENT_INIT_ACC_REALM FOREIGN KEY (REALM_ID) REFERENCES public.REALM (ID);

CREATE INDEX IDX_ASSOC_POL_ASSOC_POL_ID ON public.ASSOCIATED_POLICY(ASSOCIATED_POLICY_ID);

CREATE INDEX IDX_AUTH_EXEC_REALM_FLOW ON public.AUTHENTICATION_EXECUTION(REALM_ID, FLOW_ID);

CREATE INDEX IDX_AUTH_EXEC_FLOW ON public.AUTHENTICATION_EXECUTION(FLOW_ID);

CREATE INDEX IDX_AUTH_FLOW_REALM ON public.AUTHENTICATION_FLOW(REALM_ID);

CREATE INDEX IDX_AUTH_CONFIG_REALM ON public.AUTHENTICATOR_CONFIG(REALM_ID);

CREATE INDEX IDX_CLIENT_CLIENT_TEMPL_ID ON public.CLIENT(CLIENT_TEMPLATE_ID);

CREATE INDEX IDX_CLIENT_DEF_ROLES_CLIENT ON public.CLIENT_DEFAULT_ROLES(CLIENT_ID);

CREATE INDEX IDX_CLIENT_ID_PROV_MAP_CLIENT ON public.CLIENT_IDENTITY_PROV_MAPPING(CLIENT_ID);

CREATE INDEX IDX_CLIENT_SESSION_SESSION ON public.CLIENT_SESSION(SESSION_ID);

CREATE INDEX IDX_COMPONENT_REALM ON public.COMPONENT(REALM_ID);

CREATE INDEX IDX_COMPO_CONFIG_COMPO ON public.COMPONENT_CONFIG(COMPONENT_ID);

CREATE INDEX IDX_COMPOSITE ON public.COMPOSITE_ROLE(COMPOSITE);

CREATE INDEX IDX_COMPOSITE_CHILD ON public.COMPOSITE_ROLE(CHILD_ROLE);

CREATE INDEX IDX_CREDENTIAL_ATTR_CRED ON public.CREDENTIAL_ATTRIBUTE(CREDENTIAL_ID);

CREATE INDEX IDX_FED_CRED_ATTR_CRED ON public.FED_CREDENTIAL_ATTRIBUTE(CREDENTIAL_ID);

CREATE INDEX IDX_GROUP_ATTR_GROUP ON public.GROUP_ATTRIBUTE(GROUP_ID);

CREATE INDEX IDX_GROUP_ROLE_MAPP_GROUP ON public.GROUP_ROLE_MAPPING(GROUP_ID);

CREATE INDEX IDX_IDENT_PROV_REALM ON public.IDENTITY_PROVIDER(REALM_ID);

CREATE INDEX IDX_ID_PROV_MAPP_REALM ON public.IDENTITY_PROVIDER_MAPPER(REALM_ID);

CREATE INDEX IDX_KEYCLOAK_ROLE_CLIENT ON public.KEYCLOAK_ROLE(CLIENT);

CREATE INDEX IDX_KEYCLOAK_ROLE_REALM ON public.KEYCLOAK_ROLE(REALM);

CREATE INDEX IDX_PROTOCOL_MAPPER_CLIENT ON public.PROTOCOL_MAPPER(CLIENT_ID);

CREATE INDEX IDX_PROTO_MAPP_CLIENT_TEMPL ON public.PROTOCOL_MAPPER(CLIENT_TEMPLATE_ID);

CREATE INDEX IDX_REALM_MASTER_ADM_CLI ON public.REALM(MASTER_ADMIN_CLIENT);

CREATE INDEX IDX_REALM_ATTR_REALM ON public.REALM_ATTRIBUTE(REALM_ID);

CREATE INDEX IDX_REALM_DEF_GRP_REALM ON public.REALM_DEFAULT_GROUPS(REALM_ID);

CREATE INDEX IDX_REALM_DEF_ROLES_REALM ON public.REALM_DEFAULT_ROLES(REALM_ID);

CREATE INDEX IDX_REALM_EVT_TYPES_REALM ON public.REALM_ENABLED_EVENT_TYPES(REALM_ID);

CREATE INDEX IDX_REALM_EVT_LIST_REALM ON public.REALM_EVENTS_LISTENERS(REALM_ID);

CREATE INDEX IDX_REALM_SUPP_LOCAL_REALM ON public.REALM_SUPPORTED_LOCALES(REALM_ID);

CREATE INDEX IDX_REDIR_URI_CLIENT ON public.REDIRECT_URIS(CLIENT_ID);

CREATE INDEX IDX_REQ_ACT_PROV_REALM ON public.REQUIRED_ACTION_PROVIDER(REALM_ID);

CREATE INDEX IDX_RES_POLICY_POLICY ON public.RESOURCE_POLICY(POLICY_ID);

CREATE INDEX IDX_RES_SCOPE_SCOPE ON public.RESOURCE_SCOPE(SCOPE_ID);

CREATE INDEX IDX_RES_SERV_POL_RES_SERV ON public.RESOURCE_SERVER_POLICY(RESOURCE_SERVER_ID);

CREATE INDEX IDX_RES_SRV_RES_RES_SRV ON public.RESOURCE_SERVER_RESOURCE(RESOURCE_SERVER_ID);

CREATE INDEX IDX_RES_SRV_SCOPE_RES_SRV ON public.RESOURCE_SERVER_SCOPE(RESOURCE_SERVER_ID);

CREATE INDEX IDX_SCOPE_MAPPING_ROLE ON public.SCOPE_MAPPING(ROLE_ID);

CREATE INDEX IDX_SCOPE_POLICY_POLICY ON public.SCOPE_POLICY(POLICY_ID);

CREATE INDEX IDX_TEMPL_SCOPE_MAPP_ROLE ON public.TEMPLATE_SCOPE_MAPPING(ROLE_ID);

CREATE INDEX IDX_USR_FED_MAP_FED_PRV ON public.USER_FEDERATION_MAPPER(FEDERATION_PROVIDER_ID);

CREATE INDEX IDX_USR_FED_MAP_REALM ON public.USER_FEDERATION_MAPPER(REALM_ID);

CREATE INDEX IDX_USR_FED_PRV_REALM ON public.USER_FEDERATION_PROVIDER(REALM_ID);

CREATE INDEX IDX_WEB_ORIG_CLIENT ON public.WEB_ORIGINS(CLIENT_ID);

CREATE INDEX IDX_CLIENT_INIT_ACC_REALM ON public.CLIENT_INITIAL_ACCESS(REALM_ID);

INSERT INTO public.databasechangelog (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE) VALUES ('3.2.0', 'keycloak', 'META-I
NF/jpa-changelog-3.2.0.xml', NOW(), 42, '7:21de72ee56f1c0c861b883ac5b37c850', 'addColumn, dropPrimaryKey, dropColumn, addPrimaryKey, createTable, addPrimaryKey, addForeignKeyConstraint, createInd
ex (x45)', '', 'EXECUTED', NULL, NULL, '3.4.1');