kind: Template
apiVersion: v1
metadata:
  creationTimestamp: null
  name: keycloak
objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    creationTimestamp: null
    generation: 1
    name: keycloak-server
  spec:
    strategy:
      type: Rolling
      resources:
        limits:
          memory: 2Gi
    triggers:
    - type: ConfigChange
    test: false
    replicas: ${{REPLICAS}}
    selector:
      name: keycloak-server
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: keycloak-server
      spec:
        containers:
        - name: keycloak-server
          image: registry.devshift.net/fabric8-services/keycloak-postgres:${IMAGE_TAG}
          args:
            - '-b $(INTERNAL_POD_IP)'
            - '-Djgroups.bind_addr=global'
            - '-Djboss.node.name=$(INTERNAL_POD_IP)'
            - '-Dinfinispan.stagger.delay=0'
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 7600
              protocol: TCP
            - containerPort: 47600
              protocol: TCP
            - containerPort: 57600
              protocol: TCP
          imagePullPolicy: Always
          resources: {}
          livenessProbe:
            httpGet:
              path: /auth/realms/fabric8
              port: 8080
              scheme: HTTP
            successThreshold: 1
            failureThreshold: 5
            timeoutSeconds: 10
            periodSeconds: 5
            initialDelaySeconds: 80
          readinessProbe:
            httpGet:
              path: /auth/realms/fabric8
              port: 8080
              scheme: HTTP
            successThreshold: 1
            failureThreshold: 10
            timeoutSeconds: 5
            periodSeconds: 5
            initialDelaySeconds: 30
          terminationMessagePath: /dev/termination-log
          env:
          - name: INTERNAL_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: KEYCLOAK_USER
            valueFrom:
              secretKeyRef:
                name: keycloak-config
                key: user
          - name: KEYCLOAK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak-config
                key: password
          - name: POSTGRES_DATABASE
            valueFrom:
              secretKeyRef:
                name: keycloak-db
                key: database
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: keycloak-db
                key: user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak-db
                key: password
          - name: POSTGRESQL_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak-db
                key: admin.password
          - name: POSTGRES_PORT_5432_TCP_ADDR
            valueFrom:
              secretKeyRef:
                name: keycloak-config
                key: db.host
          - name: POSTGRES_PORT_5432_TCP_PORT
            valueFrom:
              secretKeyRef:
                name: keycloak-config
                key: db.port
          - name: OPENSHIFT_KUBE_PING_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: OPENSHIFT_KUBE_PING_LABELS
            valueFrom:
              configMapKeyRef:
                name: keycloak-config
                key: openshift.kube.ping.labels
          - name: OPENSHIFT_KUBE_PING_SERVER_PORT
            valueFrom:
              configMapKeyRef:
                name: keycloak-config
                key: openshift.kube.ping.server.port
          - name: OPERATING_MODE
            value: ${OPERATING_MODE}
          - name: JAVA_OPTS
            value: >-
              -server -Xms256m -Xmx1434m -XX:MetaspaceSize=96M
              -XX:+HeapDumpOnOutOfMemoryError
              -XX:+UseParallelGC
              -XX:MinHeapFreeRatio=20
              -XX:MaxHeapFreeRatio=40
              -XX:GCTimeRatio=4
              -XX:+PrintGCDetails
              -XX:AdaptiveSizePolicyWeight=90
              -XX:MaxMetaspaceSize=512m
              -Djava.net.preferIPv4Stack=true
              -Djboss.modules.system.pkgs=org.jboss.byteman
              -Djava.awt.headless=true
              -XX:+PrintGC
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
  status: {}
- kind: Service
  apiVersion: v1
  metadata:
    name: keycloak-server
    labels:
      name: keycloak-server
  spec:
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
    selector:
      name: keycloak-server
    type: ClusterIP
    sessionAffinity: None
  status:
    loadBalancer: {}
parameters:
- name: IMAGE_TAG
  value: latest
- name: OPERATING_MODE
  value: clustered
- name: REPLICAS
  value: "3"
